# Generated by Django 6.0.3 on 2026-06-03 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название курса')),
                ('prog_id', models.CharField(max_length=10, verbose_name='ID программы РАУЦ')),
                ('company_code', models.CharField(help_text='ППП.АУЦ.ХХХ', max_length=200, verbose_name='Код Авиакомпании')),
                ('approved', models.CharField(blank=True, max_length=200, verbose_name='Орган утвердивший программу')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
            ],
            options={
                'verbose_name': 'Курс подготовки',
                'verbose_name_plural': 'Курсы подготовки',
                'db_table': 'course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favt_cert_number', models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата ФАВТ')),
                ('favt_cert_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата выдачи сертификата ФАВТ')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Лицензия Минобразования')),
                ('license_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата выдачи лицензии Минобразования')),
            ],
            options={
                'verbose_name': 'Лицензия АУЦ',
                'verbose_name_plural': 'Лицензии АУЦ',
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('snils', models.CharField(max_length=20, unique=True, verbose_name='СНИЛС')),
                ('surname_latin', models.CharField(blank=True, max_length=100, verbose_name='Фамилия на латинице')),
                ('name_latin', models.CharField(blank=True, max_length=100, verbose_name='Имя на латинице')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Табельный номер')),
                ('dcat_id', models.PositiveIntegerField(blank=True, choices=[(1, 'Инженер (1)'), (2, 'Пилот (2)'), (3, 'Бортпроводник (3)')], null=True, verbose_name='Код профессии РАУЦ')),
                ('citizenship_code', models.CharField(default='643', max_length=3, verbose_name='Код страны гражданства ОКСМ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('aircraft_type', models.CharField(blank=True, choices=[('B737NG', 'B737NG'), ('B737CL', 'B737CL'), ('B737CL+B737NG', 'B737CL+B737NG')], max_length=30, null=True, verbose_name='Тип ВС')),
            ],
            options={
                'verbose_name': 'Слушатель',
                'verbose_name_plural': 'Слушатели',
                'db_table': 'student',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название модуля')),
                ('mod_id', models.CharField(max_length=10, verbose_name='ID модуля РАУЦ')),
                ('code', models.CharField(blank=True, help_text='ППП.АУЦ.ХХ - М.Х', max_length=50, verbose_name='Код модуля')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Плановые часы')),
                ('attachment_number', models.PositiveIntegerField(default=0, verbose_name='Номер приложения для выписки сертификата')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='api.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'module',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Зачислен'), ('in_progress', 'В процессе'), ('completed', 'Успешно завершен'), ('failed', 'Не завершен')], db_index=True, default='enrolled', max_length=30)),
                ('group', models.CharField(help_text='123.2026', max_length=30, verbose_name='Номер группы')),
                ('number_in_group', models.PositiveIntegerField(verbose_name='Порядковый номер в группе')),
                ('application', models.CharField(max_length=30, verbose_name='Номер заявки')),
                ('enrolled_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('start_sdo', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала занятий в СДО')),
                ('start_face_to_face', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала очных занятий')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('location', models.CharField(choices=[('KJA', 'Красноярск'), ('DME', 'Домодедово')], max_length=3)),
                ('addr_id', models.CharField(editable=False, max_length=10, verbose_name='Код места проведения')),
                ('dept_id', models.CharField(blank=True, editable=False, max_length=10, verbose_name='Филиал')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='api.module')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'db_table': 'enrollment',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('rauts_id', models.CharField(max_length=10, unique=True, verbose_name='ID персонала в РАУЦ')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('fptitle', models.BooleanField(default=False, verbose_name='Может оформлять документы')),
                ('tptitle', models.BooleanField(default=False, verbose_name='Может подписывать документы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник АУЦ',
                'verbose_name_plural': 'Сотрудники АУЦ',
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код/Название группы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('finalized', 'Зафиксировано'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedules', to='api.enrollment', verbose_name='Зачисление')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curator_schedules', to='api.staff', verbose_name='Куратор')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_schedules', to='api.staff', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
                'db_table': 'group_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_made', to='api.staff', verbose_name='Зачислил сотрудник'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='api.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'db_table': 'stage',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название раздела/дисциплины')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Плановые часы')),
                ('grade_type', models.CharField(choices=[('numeric', 'Числовая оценка'), ('binary', 'Бинарная (Зачтено/Не зачтено)'), ('none', 'Без оценки')], default='none', max_length=10, verbose_name='Тип оценки')),
                ('min_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная оценка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('detail', models.CharField(choices=[('sdo', 'Самостоятельная подготовка в СДО'), ('sim', '1 час - брифинг (лекция)\n4 часа - тренажерная подготовка\n1 час - дебрифинг (лекция)'), ('base-1', '1 урок (09:00 - 09:45)'), ('base-2', '2 урока (09:00 - 10:35)'), ('base-3', '3 урока (09:00 - 11:25)'), ('base-4', '4 урока (09:00 - 12:15)'), ('base-5', '5 уроков + большой перерыв 40 мин'), ('base-6', '6 уроков + большой перерыв 40 мин'), ('base-7', '7 уроков + большой перерыв 40 мин'), ('base-8', '8 уроков + большой перерыв 40 мин'), ('base-9', '9 уроков + большой перерыв 40 мин'), ('none', 'Не задано')], default='sdo', max_length=50, verbose_name='Тип расписания')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='api.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'section',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='api.student'),
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название подраздела/сессии')),
                ('detail', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип детализации (detail)')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Часы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='api.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Подраздел/Сессия',
                'verbose_name_plural': 'Подразделы/Сессии',
                'db_table': 'subsection',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('start_time', models.CharField(blank=True, help_text='Формат: ЧЧ:ММ', max_length=5, null=True, verbose_name='Время начала')),
                ('location', models.CharField(blank=True, choices=[('SDO', 'СДО'), ('DME_508', 'Домодедово, мкр. Авиационный, ул. Ильюшина, 2а, ауд. 508'), ('DME_509', 'Домодедово, мкр. Авиационный, ул. Ильюшина, 2а, ауд. 509'), ('KJA_408', 'Красноярск, ул. Маерчака, 000 ауд. 408'), ('KJA_403', 'Красноярск, ул. Маерчака, 000 ауд. 403'), ('S7 Training', 'Домодедово, пос. Битягово, строение 1'), ('Aeroflot', 'Москва, аэропорт Шереметьево'), ('UIGA', 'Ульяновск, УИГА'), ('SPBGUGA', 'Санкт Петербург, СПБГУГА')], max_length=200, null=True, verbose_name='Место')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('override_detail', models.CharField(blank=True, choices=[('sdo', 'Самостоятельная подготовка в СДО'), ('sim', '1 час - брифинг (лекция)\n4 часа - тренажерная подготовка\n1 час - дебрифинг (лекция)'), ('base-1', '1 урок (09:00 - 09:45)'), ('base-2', '2 урока (09:00 - 10:35)'), ('base-3', '3 урока (09:00 - 11:25)'), ('base-4', '4 урока (09:00 - 12:15)'), ('base-5', '5 уроков + большой перерыв 40 мин'), ('base-6', '6 уроков + большой перерыв 40 мин'), ('base-7', '7 уроков + большой перерыв 40 мин'), ('base-8', '8 уроков + большой перерыв 40 мин'), ('base-9', '9 уроков + большой перерыв 40 мин'), ('none', 'Не задано')], max_length=10, null=True, verbose_name='Переопределить тип')),
                ('group_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.groupschedule', verbose_name='Расписание')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='api.section')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedule_items', to='api.staff', verbose_name='Преподаватель')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='api.stage')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='api.subsection', verbose_name='Подподраздел')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Элементы расписания',
                'db_table': 'schedule_item',
                'ordering': ['group_schedule', 'stage__order', 'section__order', 'subsection__order'],
            },
        ),
        migrations.CreateModel(
            name='SectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_completed', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Фактические часы')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено (для бинарных/итоговых)')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('total_mark', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговая аттестация(Экзамен)')),
                ('ngroup', models.CharField(help_text='Номер группы+Номер заявки', max_length=50, verbose_name='Номер журнала')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='api.enrollment', verbose_name='Зачисление')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.section', verbose_name='Раздел')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluated_sections', to='api.staff', verbose_name='Оценил')),
            ],
            options={
                'verbose_name': 'Результат раздела',
                'verbose_name_plural': 'Результаты разделов',
                'db_table': 'section_result',
                'ordering': ['section__stage__order', 'section__order'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'section'), name='unique_enrollment_section_result')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('successful', 'Успешное прохождение'), ('attendance', 'Справка о прослушивании')], max_length=20, verbose_name='Тип сертификата')),
                ('cert_number', models.CharField(max_length=100, unique=True, verbose_name='Номер сертификата')),
                ('issued_at', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('file_path', models.FileField(blank=True, upload_to='certificates/%Y/%m/', verbose_name='Файл сертификата')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='api.enrollment', verbose_name='Зачисление/Модуль')),
                ('approved_by', models.ForeignKey(limit_choices_to={'is_active': True, 'tptitle': True}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_certificates', to='api.staff', verbose_name='Утвердил')),
                ('prepared_by', models.ForeignKey(limit_choices_to={'fptitle': True, 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_certificates', to='api.staff', verbose_name='Подготовил')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificate',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'cert_type'), name='one_cert_per_enrollment_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_stage_order_per_module'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'location'], name='idx_enroll_status_loc'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='idx_enroll_date'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'module'), name='unique_student_module_enrollment'),
        ),
    ]
