# Generated by Django 6.0.3 on 2026-05-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduleitem',
            table='schedule_item',
        ),
    ]
