# Generated by Django 6.0.3 on 2026-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scheduleitem_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_sdo',
        ),
        migrations.AddField(
            model_name='section',
            name='detail',
            field=models.CharField(choices=[('sdo', 'Самостоятельная подготовка в СДО'), ('sim', '1 час - брифинг (лекция)\n4 часа - тренажерная подготовка\n1 час - дебрифинг (лекция)'), ('base-1', '1 урок (09:00 - 09:45)'), ('base-2', '2 урока (09:00 - 10:35)'), ('base-3', '3 урока (09:00 - 11:25)'), ('base-4', '4 урока (09:00 - 12:15)'), ('base-5', '5 уроков + большой перерыв 40 мин'), ('base-6', '6 уроков + большой перерыв 40 мин'), ('base-7', '7 уроков + большой перерыв 40 мин'), ('base-8', '8 уроков + большой перерыв 40 мин'), ('base-9', '9 уроков + большой перерыв 40 мин'), ('none', 'Не задано')], default='sdo', max_length=50, verbose_name='Тип расписания'),
        ),
    ]
