# Generated by Django 6.0.3 on 2026-06-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_section_is_sdo_section_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['group_schedule', 'stage__order', 'section__order'], 'verbose_name': 'Элемент расписания', 'verbose_name_plural': 'Элементы расписания'},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='day_start_slot',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='group_code',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='override_detail',
            field=models.CharField(blank=True, choices=[('sdo', 'Самостоятельная подготовка в СДО'), ('sim', '1 час - брифинг (лекция)\n4 часа - тренажерная подготовка\n1 час - дебрифинг (лекция)'), ('base-1', '1 урок (09:00 - 09:45)'), ('base-2', '2 урока (09:00 - 10:35)'), ('base-3', '3 урока (09:00 - 11:25)'), ('base-4', '4 урока (09:00 - 12:15)'), ('base-5', '5 уроков + большой перерыв 40 мин'), ('base-6', '6 уроков + большой перерыв 40 мин'), ('base-7', '7 уроков + большой перерыв 40 мин'), ('base-8', '8 уроков + большой перерыв 40 мин'), ('base-9', '9 уроков + большой перерыв 40 мин'), ('none', 'Не задано')], max_length=10, null=True, verbose_name='Переопределить тип'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='start_time',
            field=models.CharField(blank=True, help_text='Формат: ЧЧ:ММ', max_length=5, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.CharField(help_text='123.2026', max_length=30, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='group_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.groupschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedule_items', to='api.staff', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Зафиксировано'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='location',
            field=models.CharField(blank=True, choices=[('SDO', 'СДО'), ('DME_508', 'Домодедово, мкр. Авиационный, ул. Ильюшина, 2а, ауд. 508'), ('DME_509', 'Домодедово, мкр. Авиационный, ул. Ильюшина, 2а, ауд. 509'), ('KJA_408', 'Красноярск, ул. Маерчака, 000 ауд. 408'), ('KJA_403', 'Красноярск, ул. Маерчака, 000 ауд. 403'), ('S7 Training', 'Домодедово, пос. Битягово, строение 1'), ('Aeroflot', 'Москва, аэропорт Шереметьево'), ('UIGA', 'Ульяновск, УИГА'), ('SPBGUGA', 'Санкт Петербург, СПБГУГА')], max_length=200, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='is_sdo',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='time_slot',
        ),
    ]
