# Generated by Django 6.0.3 on 2026-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_scheduleitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='group_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код/Название группы'),
        ),
    ]
